### ISSUE TITLE
Reverse pattern direction works but displays odd message

### ISSUE THREAD

**Issue by demory** [catalogueglobal/datatools-ui#104]
<img width="676" alt="image" src="https://user-images.githubusercontent.com/653100/39543915-74339098-4e1a-11e8-91f1-85f0522b3c44.png">

**Comment by landonreed** [comment]
I will clarify this message.  Basically, the reverse trip pattern feature is prohibited for any pattern that has trips because it does not conform to the internal rule to only move one pattern stop at a time, which ensures that the pattern's stop times can be rearranged in a predictable way.  Perhaps the right move is to only allow reversing patterns for patterns with no trips.
