### ISSUE TITLE
Basic editing Patterns

### ISSUE THREAD

**Issue by WEMAPP** [catalogueglobal/datatools-ui#17]
Hi, I'm trying to change the geometry of a pattern. Moving on the map the x of the handler geometry does not change but returns to the existing line. To make these changes, you need to load a shapefile from the toolbar? If so, the system gives me the error that the zip file is invalid (.zip). How do I fix it?
Thanks

**Comment by landonreed** [comment]
Apologies for the non-response. The pattern editing has changed extensively on the dev branch since this issue was tagged, so I will close. But feel free to re-open if your issue persists.

To answer the question about the shapefile upload, that is only to draw a set of polylines as an overlay on the basemap -- intended to give users a point of reference when creating patterns, but nothing beyond that.
