### ISSUE TITLE
Mapzen shutdown: Replace turn-by-turn valhalla API calls

### ISSUE THREAD

**Issue by WEMAPP** [catalogueglobal/datatools-ui#60]
Hi, Mapzen is shutting down its services. 
are you planning to change the project api of turn by turn to solve this situation? 

thank you

https://mapzen.com/blog/shutdown/

**Comment by landonreed** [comment]
Yes, we will be updating the turn-by-turn endpoint to use an alternative service.  I will update this issue with the progress.

**Comment by WEMAPP** [comment]
hi, are there any news for the iusse? thank you

**Comment by landonreed** [comment]
Hi, I'm working on a fix and should have it ready by tomorrow.  Many other routing services have more restrictive terms of service than Mapzen, so we have settled on [GraphHopper's routing API](https://graphhopper.com/api/1/docs/routing/).  However, any users of this feature in datatools-ui should be aware that in order to use their API in this context, they must have a white label agreement with GraphHopper.

**Comment by landonreed** [comment]
The tag [`v2.0.3`](https://github.com/catalogueglobal/datatools-ui/tree/v2.0.3) now contains a fix for this issue (along with some other pattern editing fixes).  However, until development on the `sql-editor` branch wraps up, this fix will not be available in the dev branch, which (among other things) contains updates for using an RDBMS for storing GTFS.

Note: there are some failing tests on this tag, but they appear to be related to the bug fixed on dragging a pattern control point.  The failing tests may not be updated because this is not the active development branch.  Nevertheless, the control point dragging is working properly.
