### ISSUE TITLE
Disabling authenticaion possible?

### ISSUE THREAD

**Issue by typhoon2099** [catalogueglobal/datatools-ui#71]
It looks like Auth0 has removed the ability to get `user_metadata` and `app_metadata` from the `/userinfo` endpoint, which is breaking authentication for me. Is there a way I can disable authentication completely? I'm trying to deploy this project for a client so if it is indeed possible then I'll hide the app behind an nginx proxy and require authentication through that.

Side question: Which branches/tags should I be using for datatools-server and datatools-ui? I'm pretty confused as to which branches go together (mostly because I haven't been able to log into the system yet).

**Comment by landonreed** [comment]
The `DISABLE_AUTH` property in `env.yml` (for both datatools-ui and datatools-server) can be used to turn off authentication.

As for which branches to use, we recommend only using released versions rather than using some combination of branches, which are primarily used for active development and may be unstable.  We can better document which releases ought to be used in tandem, but the 2.x.x for both ui and server should be a safe combination.  These do use MapDB for persistence, so they will be different from the dev environment using Mongo and Postgres.

**Comment by typhoon2099** [comment]
`DISABLE_AUTH` doesn't appear to do anything on the frontend, and I don't see anything in the frontend code which references it. I've tried clearing out the Auth0 related env variables but that just causes the frontend to error out (`Error: `ClientID` required as first parameter.`).

I'm using the `v2.0.4` release for the frontend and the `v2.0.1` release for the backend. I've also tried the `v4.0.0` frontend release as it was released the same day as the `v2.0.1` version of the backend, but the same issues arose. Can you please give me exact releases to use which work together? I still haven't found a matching pair (or at least not one that will allow me to disable the currently broken authentication).

**Comment by thomasrm** [comment]
Hi, 
I'd like to disable the authentication. I've set DISABLE_AUTH to false in both datatools-ui and datatools-server env.yml, but nothing changes in the frontend. 
Is there anything else to do?
